# Stubs for pymonetdb.sql.types (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

CHAR: str
VARCHAR: str
CLOB: str
BLOB: str
TINYINT: str
SMALLINT: str
INT: str
BIGINT: str
HUGEINT: str
SERIAL: str
REAL: str
DOUBLE: str
DECIMAL: str
BOOLEAN: str
DATE: str
TIME: str
TIMESTAMP: str
MONTH_INTERVAL: str
SEC_INTERVAL: str
URL: str
INET: str
UUID: str
JSON: str
GEOMETRY: str
GEOMETRYA: str
SHORTINT: str
MEDIUMINT: str
LONGINT: str
OID: str
WRD: str
FLOAT: str
TIMESTAMPTZ: str
TIMETZ: str
INTERVAL: str
CHARACTER = CHAR
CHARACTER_VARYING = VARCHAR
CHARACHTER_LARGE_OBJECT = CLOB
BINARY_LARGE_OBJECT = BLOB
NUMERIC = DECIMAL
DOUBLE_PRECISION = DOUBLE
